// Code generated by MockGen. DO NOT EDIT.
// Source: chats.go

// Package mock_api is a generated GoMock package.
package mock_api

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "hitalent_tt/model"
)

// MockСhatStorage is a mock of СhatStorage interface.
type MockСhatStorage struct {
	ctrl     *gomock.Controller
	recorder *MockСhatStorageMockRecorder
}

// MockСhatStorageMockRecorder is the mock recorder for MockСhatStorage.
type MockСhatStorageMockRecorder struct {
	mock *MockСhatStorage
}

// NewMockСhatStorage creates a new mock instance.
func NewMockСhatStorage(ctrl *gomock.Controller) *MockСhatStorage {
	mock := &MockСhatStorage{ctrl: ctrl}
	mock.recorder = &MockСhatStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockСhatStorage) EXPECT() *MockСhatStorageMockRecorder {
	return m.recorder
}

// CreateChat mocks base method.
func (m *MockСhatStorage) CreateChat(tittle string) (*model.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", tittle)
	ret0, _ := ret[0].(*model.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockСhatStorageMockRecorder) CreateChat(tittle interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockСhatStorage)(nil).CreateChat), tittle)
}

// DeleteChat mocks base method.
func (m *MockСhatStorage) DeleteChat(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockСhatStorageMockRecorder) DeleteChat(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockСhatStorage)(nil).DeleteChat), id)
}

// GetChatByID mocks base method.
func (m *MockСhatStorage) GetChatByID(chatId, messageCount int) (*model.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatByID", chatId, messageCount)
	ret0, _ := ret[0].(*model.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatByID indicates an expected call of GetChatByID.
func (mr *MockСhatStorageMockRecorder) GetChatByID(chatId, messageCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatByID", reflect.TypeOf((*MockСhatStorage)(nil).GetChatByID), chatId, messageCount)
}

// SendMessage mocks base method.
func (m *MockСhatStorage) SendMessage(chatID int, text string) (*model.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", chatID, text)
	ret0, _ := ret[0].(*model.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockСhatStorageMockRecorder) SendMessage(chatID, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockСhatStorage)(nil).SendMessage), chatID, text)
}
